### ISSUE TITLE
Provide docker.j4care.com/mariadb image with replication support

### ISSUE THREAD

**Issue by petrkalina** [j4care/dcm4chee-arc-light-pro-issues#24]
provide image for mariadb with replication support

```
REPOSITORY                              TAG                    IMAGE ID       CREATED          SIZE
docker.j4care.com/mariadb               11.5.2-1               0005a01b27d9   4 minutes ago    407MB
```

replication config:

- arc1 yml
```
  mariadb:
    image: docker.j4care.com/mariadb:11.5.2-1
...
    command:
      - "--log-bin"
      - "--log-basename=node1"
      - "--server-id=1"
      - "--replicate-do-db=keycloak"
      - "--auto_increment_increment=2"
      - "--auto_increment_offset=1"
      - "--character-set-server=latin1"
      - "--collation-server=latin1_general_cs"
      - "--max_allowed_packet=32505856"
..
    extra_hosts:
      - "master:192.168.2.181"
```
- arc2 yml
```
  mariadb:
    image: docker.j4care.com/mariadb:11.5.2-1
..
    command:
      - "--log-bin"
      - "--log-basename=node2"
      - "--server-id=2"
      - "--replicate-do-db=keycloak"
      - "--auto_increment_increment=2"
      - "--auto_increment_offset=2"
      - "--character-set-server=latin1"
      - "--collation-server=latin1_general_cs"
      - "--max_allowed_packet=32505856"
..

    extra_hosts:
      - "master:192.168.2.188"
```

steps:

- prepare replication
```
arc1$ docker exec $(docker ps -q -f name=arc_mariadb.1) prepare-replication
arc2$ docker exec $(docker ps -q -f name=arc_mariadb.1) prepare-replication
```
- enable replication
```
arc1$ docker exec $(docker ps -q -f name=arc_mariadb.1) show-master-status
File	Position	Binlog_Do_DB	Binlog_Ignore_DB
node1-bin.000006	342		

arc2$ docker exec $(docker ps -q -f name=arc_mariadb.1) show-master-status
File	Position	Binlog_Do_DB	Binlog_Ignore_DB
node2-bin.000005	346		

arc1$ docker exec $(docker ps -q -f name=arc_mariadb.1) enable-replication node2-bin.000005 346
arc2$ docker exec $(docker ps -q -f name=arc_mariadb.1) enable-replication node1-bin.000006 342
```
- check slave status
```
arc1$ docker exec $(docker ps -q -f name=arc_mariadb.1) show-slave-status
..
             Slave_IO_Running: Yes
             Slave_SQL_Running: Yes

arc2$ docker exec $(docker ps -q -f name=arc_mariadb.1) show-slave-status
..
             Slave_IO_Running: Yes
             Slave_SQL_Running: Yes
```
