### ISSUE TITLE
docker image 'docker.j4care.com/rm-wildfly-logs' to provide a cron service for daily deletion arc/viewer/visuapps logs

### ISSUE THREAD

**Issue by petrkalina** [j4care/dcm4chee-arc-light-pro-issues#32]
see:

- dcm4che/dcm4chee-arc-light#4593
- available from 5.33.1-4 installation template
- adjusted [Install Viewer](https://docs.j4care.com/pro/installation/pro-installation-swarm-install-viewer.md)
- adjusted [Install Archive](https://docs.j4care.com/pro/pro-installation.md#single-site-installation)

j4c image: 

```
docker.j4care.com/rm-wildfly-logs:1.0.0-1
```

example:

- arc-psql.yml
```
  arc-rm-logs:
    image: docker.j4care.com/rm-wildfly-logs:1.0.0-1
    environment:
      WILDFLY_SERVER_LOG_DIRS: /opt/wildfly/standalone/log
      ARC_HL7_LOG_DIRS: /hl7-log
      WILDFLY_SERVER_LOG_RETENTION_DAYS: 7
      WILDFLY_AUDIT_LOG_RETENTION_DAYS: 7
      ARC_HL7_LOG_RETENTION_DAYS: 7
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/archive-wildfly/log:/opt/wildfly/standalone/log
      - /data/archive-hl7-log:/hl7-log
    networks:
      - j4c
    deploy:
      placement:
        constraints: [node.hostname == test-arc]
```
- viewer.yml
```
  viewer-rm-logs:
    image: docker.j4care.com/rm-wildfly-logs:1.0.0-1
    environment:
      WILDFLY_SERVER_LOG_DIRS: /opt/wildfly/standalone/log
      WILDFLY_SERVER_LOG_RETENTION_DAYS: 7
      WILDFLY_AUDIT_LOG_RETENTION_DAYS: 7
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/viewer/log:/opt/wildfly/standalone/log
    networks:
      - j4c
    deploy:
      placement:
        constraints: [node.hostname == viewer1]

...

  visuapps-rm-logs:
    image: docker.j4care.com/rm-wildfly-logs:1.0.0-1
    environment:
      WILDFLY_SERVER_LOG_DIRS: /opt/wildfly/standalone/log
      WILDFLY_SERVER_LOG_RETENTION_DAYS: 7
      WILDFLY_AUDIT_LOG_RETENTION_DAYS: 7
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/visuapps/log:/opt/wildfly/standalone/log
    networks:
      - j4c
    deploy:
      placement:
        constraints: [node.hostname == viewer1]
```
