### ISSUE TITLE
Provide docker.j4care.com/nfs-quota image

### ISSUE THREAD

**Issue by petrkalina** [j4care/dcm4chee-arc-light-pro-issues#39]
Provide cron service for NFS quota monitoring. Example compose block:

```
  arc-nfs-quota:
    image: docker.j4care.com/nfs-quota:1.0.0-1
    environment:
      USED_BLOCKS_FILE: /nfs-quota/used-blocks.txt
    volumes:
      - /data-dcm/cache:/nfs-quota
    networks:
      - j4c
    deploy:
      placement:
        constraints: [node.hostname == arc1]
```

with:

`USED_BLOCKS_FILE` - path of the file to write the used blocks info to. Default setting: `/nfs-quota/used-blocks.txt`.

image:

```
REPOSITORY                                 TAG               IMAGE ID       CREATED         SIZE
docker.j4care.com/nfs-quota                1.0.0-1           225044278d3d   19 hours ago    202MB
```

related to: https://github.com/dcm4che/dcm4chee-arc-light/issues/4584
